### ISSUE TITLE
MPU9250BasicAHRS/ MPU9250BasicAHRS.ino :  I AM FF I should be 71

### ISSUE THREAD

**Issue by jonathanrjpereira** [shubhampaul/Real_Time_Planet_Tracking_System#2]
9-DOF 16-bit
motion sensor
60 ug LSB
MPU9250 I AM FF I should be 71
MPU9250
I AM
FF
I Should Be
71
Could not connect to MPU9250: 0xFF

**Comment by shubhampaul** [comment]
This is shown when there is a hardware problem. Please check your wiring.

**Comment by jonathanrjpereira** [comment]
Can you provide the correct wiring schematic with the Arduino UNO?
I have connected the VCC to 3.3V, GND, SCL to A5 & SDA to A4. Am I missing any other connections

**Comment by shubhampaul** [comment]
No, you are not missing anything.The above issue can be caused by:
1.SCL and SDA wires are too long (I2C doesn't work properly on long wires)
2.Try connecting them directly with jumper wires (in case you are not). Hand soldered boards causes problems when SDA and SCL are too close (capacitance and inductance).
3.Make sure the grounding is proper. MCU (uno) GND directly connected to MPU's GND.
4.Also there are separete SCL /SDAs on UNO diagonally opposite to A5/A4 (might be helpful -not a real solution)

**Comment by shubhampaul** [comment]
5.Also try using the 5v supply instead of 3v to VCC.

**Comment by jonathanrjpereira** [comment]
It's a new sensor. Max length of the SDA & SCL lines are 10cm. Could be because I haven't connected external pull ups
